version: "3.8"

services:
  scrapy:
    build: .
    command: bash
    volumes:
      - .:/usr/src/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/boe_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/boe_test
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
